Invoice = float(input("Please Enter The Total Invoice Amount :"))
Tax_value = float(input("Pleas Enter Tax Value :"))
people = int(input("Enter How Many Of People :"))
Tax_calculation = float((Tax_value / 100) * Invoice)
The_Final_Total = float(Tax_calculation + Invoice)
A_Person_share = float(The_Final_Total / people)
print(f"Tax value amount: {Tax_calculation}")
print(f"The total amount of the invoice:  {Invoice}")
print(f" Total invoice amount after tax {The_Final_Total}")
print(f" A person's share : {A_Person_share}")
